#!/usr/bin/env php
<?php

declare(strict_types=1);

use InspectaAi\Console\Application;

error_reporting(\E_ALL & ~\E_DEPRECATED & ~\E_USER_DEPRECATED);

set_error_handler(static function (int $severity, string $message, string $file, int $line): bool {
    if (0 !== ($severity & error_reporting())) {
        throw new \ErrorException($message, 0, $severity, $file, $line);
    }

    return true;
});

// author: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/php-cs-fixer
// load dependencies
(static function (): void {
    $require = true;
    if (class_exists('Phar')) {
        // Maybe this file is used as phar-stub? Let's try!
        try {
            \Phar::mapPhar('inspecta-ai.phar');

            /** @phpstan-ignore requireOnce.fileNotFound */
            require_once 'phar://inspecta-ai.phar/vendor/autoload.php';

            $require = false;
        } catch (\PharException $e) {
        }
    }

    if ($require) {
        // OK, it's not, let give Composer autoloader a try!
        $possibleFiles = [__DIR__.'/../../autoload.php', __DIR__.'/../autoload.php', __DIR__.'/vendor/autoload.php'];
        $file = null;
        foreach ($possibleFiles as $possibleFile) {
            if (file_exists($possibleFile)) {
                $file = $possibleFile;

                break;
            }
        }

        if (null === $file) {
            throw new \RuntimeException('Unable to locate autoload.php file.');
        }

        require_once $file;
    }
})();

$application = new Application();
$application->run();

__HALT_COMPILER();
